inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Max: 7
  Exclude:
    - 'bin/bundle'

  Style/Documentation:
    Enabled: false

  Style/ClassAndModuleChildren:
    Enabled: false

  Sytle/IfUnlessModifier:
    Enabled: false

  Metrics/BlockLength:
    Exclude:
      - 'spec/**/*'
      - 'app/controllers/swagger/**/*'

  AllCops:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
